### PR TITLE
Add "Autoplay Speed" field to Slick Slider-based elements

### PR DESCRIPTION
**Pull request by gnowland**
Hi Andrew,

I’ve added an input field to adjust the slide "pause" duration for all Slick Slider-based elements:
- Carousel
- Gallery (Carousel and Slideshow layout)
- Posts (Carousel layout)

“Autoplay Speed” field is displayed conditionally when "Autoplay" is set to `on`. "Autoplay Speed" is in milliseconds.

I wasn’t sure what your preferred PR process was because I couldn’t find any contributing guidelines, so I only committed un-compiled (src) files… if you need anything else let me know.

Great project, very clean codebase — I hope to commit more in the future! 🙂

### CODE REVIEW

**Comment by gnowland** [comment]
Came across a possible bug in production where when Tailoring the page (Customizer) the slide speed is set as undefined (0ms), investigating further.

**Comment by gnowland** [comment]
Fixed the issue.

**Comment by andrew-worsfold** [comment]
Thanks for the effort here, @gnowland!  Much appreciated!

**Comment by gnowland** [comment]
Glad to help @andrew-worsfold -- fantastic plugin, I hope to contribute more pull requests in the future!

**Pull request merged**
