### PR TITLE
Small background images do not have the 'thumbnail' size.

### PR DESCRIPTION
**Pull request by dtbaker**
Also need some sort of 'default' background size option that isn't Cover or Contain, so that we can repeat background images correctly.

Here's an example small background image that I was trying to make repeating on a Row/Section and can be used to trigger this javascript error.

grey-tile

Don't feel you have to merge my shitty code, just see where the bug is and implement your own better fix :) :+1:

### CODE REVIEW

**Comment by dtbaker** [comment]
Also was unable to get both a background image and color working at the same time (until I removed that rgba and gradient code)

**Comment by andrew-worsfold** [comment]
The purpose of the code in includes/helpers/helpers-elements.php was to allow background colours to be used over background images (https://css-tricks.com/tinted-images-multiple-backgrounds/).  I've changed this to "linear-gradient( {$atts['background_color']}, {$atts['background_color']} ), url({$background_image_src}) center center no-repeat" and that appears to work.  Can you please confirm if this works for you too?

The rest of the changes look good!

Below is a screenshot of this working in my environment (blue semi-transparent background over a simple repeating pattern).  

screen shot 2016-07-11 at 6 29 25 pm

Using a colour with full opacity means that only the colour is visible..

**Comment by dtbaker** [comment]
Oh cool! That's an interesting technique for applying a color over the "top" of a background image in one hit. I'll keep that in mind for future projects.  I was trying to do the reverse of this, a background image over the top of a solid color. 

So I got techniques working side by side now. Both columns have the same repeating background image. The left column has a transparent background color, so this applies a tint to the image. The right column has a solid background color, so this now goes behind the background image like we need (something that wasn't possible before). 

image

**Comment by andrew-worsfold** [comment]
I've merged these changes.  I'll make a separate commit to apply this to the Gallery image and minify sidebar.js.

**Pull request merged**
