### PR TITLE
Dynamic CSS preview improvement

### PR DESCRIPTION
**Pull request by reefki**
Border width dynamic CSS update missing old format delimiter check

### CODE REVIEW

**Comment by reefki** [comment]
Fallback color to `initial` if the value is empty, because previously when I select a color for example `#ddd3d3` then I click on "Clear" button the color on preview still `#ddd3d3`

**Comment by reefki** [comment]
The same behavior also found in border width, if value is empty the CSS still uses previous value, better to fallback to `0` if value is empty.

**Comment by andrew-worsfold** [comment]
Hi @reefki -

The 1.7.2 release made a number of improvements to the generation and application of custom CSS rules.  The issue here should be resolved as a result.  Could you please let me know if things are working as expected from your side?

Cheers,
Andrew.

**Comment by reefki** [comment]
Hi @andrew-worsfold 

Thanks for the update, really lots of improvements! Love it.

However, I still facing some problem with border, take a look below:

screen capture on 2016-11-01 at 14-52-33

**Comment by andrew-worsfold** [comment]
Good catch there.  That was actually due to the validation function being used for the border style setting.  This should be resolved in the latest commit (1.7.3)..

**Comment by andrew-worsfold** [comment]
@reefki -

If this is now working for you, we can close out this PR.

**Comment by reefki** [comment]
@andrew-worsfold Yep everything works great now! Feel free to close.

Thanks

**Pull request closed without merging**
